trigger: none

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureCLI@2
  displayName: 'Add devops IP to Postgres firewall'
  inputs:
    scriptType: bash
    scriptLocation: inlineScript
    azureSubscription: 'S174t.azdo-deployment'
    inlineScript: |
      runnerIP=$(curl -s https://icanhazip.com)

      az postgres flexible-server firewall-rule create \
        --subscription "$(PROD_DB_SUBSCRIPTION)" \
        --resource-group "$(PROD_DB_RG)" \
        --name "$(PROD_DB_RESOURCE_NAME)" \
        --rule-name allow-devops-runner \
        --start-ip-address "$runnerIP" \
        --end-ip-address "$runnerIP"

- template: templates/sync-and-init-db.yml

- task: AzureCLI@2
  displayName: 'Remove devops IP from Postgres firewall'
  condition: always()
  inputs:
    scriptType: bash
    scriptLocation: inlineScript
    azureSubscription: 'S174t.azdo-deployment'
    inlineScript: |
      az postgres flexible-server firewall-rule delete --yes \
        --subscription "$(PROD_DB_SUBSCRIPTION)" \
        --resource-group "$(PROD_DB_RG)" \
        --name "$(PROD_DB_RESOURCE_NAME)" \
        --rule-name allow-devops-runner \
